### ISSUE TITLE
Support for Bag-Size tag

### ISSUE THREAD

**Issue by henning-gerhardt** [whikloj/BagItTools#15]
In extended mode of creating a bag the oxum value is generated with total of file size and amount of files in the `data` directory. The total file size could be used to fill the `Bag-Size` tag with a human readable value of the total file size.

**Comment by whikloj** [comment]
Resolved with https://github.com/whikloj/BagItTools/commit/667ae0b10fa784d0eaafe0521d635f4bee66f3ff
