### ISSUE TITLE
Path issues on a Windows environment

### ISSUE THREAD

**Issue by jonasraoni** [whikloj/BagItTools#45]
Hi @whikloj!

We're using your package to preserve academic journals at @pkp, and some users had issues under Windows, which I've just confirmed by my own.

Are you open for contributions? For now I saw just two issues:
- Path issues
The package is failing to format the path properly in some cases (e.g. trying to open `/c:/bag`).

- The repository cannot be even cloned in Windows without hacks, due to invalid file names (below I've left the offending entries):
```
tests/resources/TestBadFilePathsBag/data/this-file-will-be-fine-%-and-
.txt

tests/resources/TestEncodingBag/data/carriage
return-file.txt

tests/resources/TestEncodingBag/data/directory
line
break/carriage
return/Example-file-%-and-%25.txt

tests/resources/TestEncodingBag/data/directory
line
break/some-file.txt
```

p.s.: About the cloning problem, that's not a real issue for us, as `composer` is "fixing" the paths by itself.

**Comment by whikloj** [comment]
Hi @jonasraoni,

I'm more than happy to accept contributions if it helps. I have not yet, but have considered trying to setup Windows under Github Actions. If you have any experience with that I'd love it.

As for the filenames, those tests might be overkill. I'll have a look and see if I can replicate the test generated test objects.

**Comment by jonasraoni** [comment]
Hi @whikloj!

I've left a PR here:
- https://github.com/whikloj/BagItTools/pull/46

I tried to organize the commits, and left some comments to make it easier to review 👀

About the problematic files, I've removed them and updated the tests, let me know if you're ok with it.

**Comment by whikloj** [comment]
Resolved with https://github.com/whikloj/BagItTools/commit/f2496ced53cee2ab6aceda965d2f70cf5c755311
