### ISSUE TITLE
Bag::loadTagManifests() leaves $this->tagManifests uninitialized if bag files count is 0

### ISSUE THREAD

**Issue by zozlak** [whikloj/BagItTools#54]
If the [early-return condition of Bag::loadTagManifest()](https://github.com/whikloj/BagItTools/blob/main/src/Bag.php#L1644-L1646) is met, the `$this->tagManifests` property is left uninitialized leading to the `Undefined property: whikloj\BagItTools\Bag::$tagManifests` error, e.g. on a `$bag->validate()` call (because of [this line](https://github.com/whikloj/BagItTools/blob/935441ef2f2def90caa180f5a6b6f547c79dbe5f/src/Bag.php#L356)).

A solution would be to set `$this->tagManifests` before returning, e.g.:
```php
    private function loadTagManifests(): bool
    {
        $tagManifests = [];
        $pattern = $this->getBagRoot() . "/tagmanifest-*.txt";
        $files = BagUtils::findAllByPattern($pattern);
        if (count($files) < 1) {
            # ADDED LINE:
            $this->tagManifests = $tagManifests;
            return false;
        }
        (...)
    }
```

**Comment by whikloj** [comment]
Hi @zozlak, could you give me an example of what you did to hit this particular situation? I'm just wondering if I'm missing something elsewhere.

**Comment by zozlak** [comment]
```php
$bag   = whikloj\BagItTools\Bag::load('TestFilesBag.tgz');
$bag->isValid();
```
The `Undefined property: whikloj\BagItTools\Bag::$tagManifests` error is thrown by the second line.
You can download the test bag file from https://github.com/acdh-oeaw/repo-file-checker/blob/master/_testFiles/BagItTest/bagit/TestFilesBag.tgz

**Comment by whikloj** [comment]
Thanks for bringing this up @zozlak, this should resolve the issue. Let me know if it's good for you.

**Comment by zozlak** [comment]
[Here](https://github.com/whikloj/BagItTools/blob/main/src/Bag.php#L1255) you unset the `$this->tagManifests` and I would expect running `is_array($this->tagManifests)` [here](https://github.com/whikloj/BagItTools/pull/55/files#diff-334b2a40d5b8e61f537801d64184335c6305dc06495125a2ffeab776edde6f1fR354) on an unset property will end up with a `Undefined property: Bag::$tagManifests`, wouldn't it?

But
```php
if (count($this->tagManifests ?? []) > 0) {
    (...)
}
```
should do the job.

**Comment by whikloj** [comment]
It's the call to `$this->ensureTagManifests();` in `loadTagManifests` (line 1641 of `Bag.php`) that ensures it is setup.

**Comment by zozlak** [comment]
Right!

I can confirm no error is thrown now.

**Comment by zozlak** [comment]
Could you please make a release including this patch?

**Comment by whikloj** [comment]
Sorry I was trying to think of anything else I might want to do but then dropped it. I have pushed out 4.2.3
