### ISSUE TITLE
End support for PHP 5.6 & 7.1

### ISSUE THREAD

**Issue by whikloj** [whikloj/BagItTools#7]
My plan is that the next major release (2.0.0) of BagItTools will require PHP 7.2.

@henning-gerhardt, @mjordan, @elizoller does this change in requirements cause any concerns?

I know that [islandora_bagger](https://github.com/mjordan/islandora_bagger/blob/master/composer.json#L13) currently requires `7.1.3`. If it is more desirable I can move to a PHP 7.1 requirement for the 2.0.0 version and PHP 7.2 for 3.0.0.

Just trying to see how many versions I need to maintain.

**Comment by mjordan** [comment]
I'll test Islandora Bagger with a 7.2 minimum requirement and let you know how it goes.

**Comment by mjordan** [comment]
@whikloj As of 978810f11620c0eead22876e338f87bba77fcacc Islandora Bagger requires "php": "^7.2".

**Comment by henning-gerhardt** [comment]
@whikloj : No problem to go with PHP 7.2 as Debian 10 is providing PHP 7.3.

**Comment by whikloj** [comment]
Perfect, thank you.

**Comment by elizoller** [comment]
No problem from my perspective either.

**Comment by whikloj** [comment]
Resolved with https://github.com/whikloj/BagItTools/commit/fdff8e354f9ee76846d0583d6b1294ad48b4ddce
